import {StyleSheet, Platform} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  content: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    marginTop: Platform.OS === 'ios' ? 60 : 20, // push down slightly like a sheet
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: {width: 0, height: -10},
    shadowRadius: 40,
    elevation: 20,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 16,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1A1B25',
  },
  closeBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F4F6F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  formArea: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 24,
  },
  segmentedControl: {
    flexDirection: 'row',
    height: 48,
    backgroundColor: '#F4F6F9',
    borderRadius: 24,
    padding: 4,
    marginBottom: 40,
    shadowColor: '#000',
    shadowOpacity: 0.02,
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 4,
    elevation: 1,
  },
  segment: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
  },
  segmentActive: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#5c11d4',
    shadowOpacity: 0.08,
    shadowOffset: {width: 0, height: 4},
    shadowRadius: 12,
    elevation: 2,
  },
  segmentText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#8D93A5',
  },
  segmentTextActive: {
    color: '#5c11d4',
  },
  inputSection: {
    marginBottom: 32,
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#8D93A5',
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 2,
    borderBottomColor: '#E2E6EE',
  },
  inputIcon: {
    marginRight: 12,
    paddingBottom: 8,
  },
  hugeInput: {
    flex: 1,
    height: 72,
    fontSize: 32,
    fontWeight: '700',
    color: '#1A1B25',
    paddingBottom: 8,
    letterSpacing: -0.5,
  },
  normalInput: {
    flex: 1,
    height: 48,
    fontSize: 18,
    fontWeight: '500',
    color: '#1A1B25',
    paddingBottom: 8,
  },
  inputHelp: {
    fontSize: 14,
    color: '#8D93A5',
    marginTop: 16,
  },
  footer: {
    padding: 24,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#F4F6F9',
  },
  deployBtn: {
    height: 64,
    backgroundColor: '#5c11d4',
    borderRadius: 32,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#5c11d4',
    shadowOpacity: 0.25,
    shadowOffset: {width: 0, height: 8},
    shadowRadius: 24,
    elevation: 8,
    gap: 8,
  },
  deployBtnDisabled: {
    backgroundColor: '#E2E6EE',
    shadowOpacity: 0,
    elevation: 0,
  },
  deployBtnText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
  },
});
