import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F6F9',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 48,
    paddingBottom: 24,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1A1B25',
    letterSpacing: -0.5,
  },
  headerSubtitle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#8D93A5',
    marginTop: 4,
    letterSpacing: 1,
  },
  settingsBtn: {
    width: 40,
    height: 40,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 8,
    elevation: 2,
  },
  mainContent: {
    paddingHorizontal: 24,
    paddingTop: 8,
    paddingBottom: 120,
    gap: 24,
  },
  heroSection: {
    alignItems: 'center',
    gap: 24,
    marginBottom: 8,
  },
  heroButton: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#5c11d4',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#5c11d4',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 12},
    shadowRadius: 32,
    elevation: 8,
  },
  heroButtonInactive: {
    backgroundColor: '#8D93A5',
    shadowColor: '#8D93A5',
  },
  heroTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#1A1B25',
    marginBottom: 4,
  },
  heroSubtitle: {
    fontSize: 16,
    color: '#8D93A5',
    fontWeight: '500',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    shadowColor: '#5c11d4',
    shadowOpacity: 0.04,
    shadowOffset: {width: 0, height: 12},
    shadowRadius: 32,
    elevation: 8,
    marginBottom: 4, // Prevents bottom shadow clipping if gap acts up
  },
  strictnessHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1A1B25',
  },
  cardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cardTextContainer: {
    flex: 1,
    marginRight: 16,
  },
  cardSubtitle: {
    fontSize: 14,
    fontWeight: '500',
    color: '#8D93A5',
    marginTop: 4,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F4F6F9',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 12,
  },
  strictnessInput: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1A1B25',
    padding: 0,
    minWidth: 32,
    textAlign: 'center',
  },
  inputSuffix: {
    fontSize: 16,
    fontWeight: '600',
    color: '#8D93A5',
    marginLeft: 2,
  },
  sliderLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  sliderLabelText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#8D93A5',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  statsContainer: {
    flexDirection: 'row',
    gap: 16,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 20,
    shadowColor: '#5c11d4',
    shadowOpacity: 0.04,
    shadowOffset: {width: 0, height: 12},
    shadowRadius: 32,
    alignItems: 'flex-start',
  },
  iconCircleRed: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 90, 95, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconCircleGreen: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(46, 210, 153, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statNumber: {
    fontSize: 32,
    fontWeight: '700',
    color: '#1A1B25',
    lineHeight: 32,
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#8D93A5',
    letterSpacing: 0.5,
  },
});
